In [16]:
import numpy as np
from collections import defaultdict
import pandas as pd
import matplotlib.pyplot as plt
import pickle

In [17]:
!ls repo

heuristics_result_2.pkl  heuristics_result_4.pkl

In [25]:
with open("repo/heuristics_result_4.pkl", 'rb') as f:
    res = pickle.load(f)
    #얘 4-16임.

In [26]:
df = pd.DataFrame(res).transpose()

In [27]:
df

           DM_DS_RTA_LC  DM_RTA_LC  DkC_RTA_LC  OPA_DA_LC  SM_DS_RTA_LC
4 16 0.10         10000      10000       10000      10000         10000
     0.20         10000      10000       10000      10000         10000
     0.30          9972       9972        9972      10000          9972
     0.40          9913       9913        9913      10000          9913
     0.50          9746       9746        9746      10000          9746
     0.60          9502       9502        9497      10000          9497
     0.70          9210       9213        9197      10000          9197
     0.80          8801       8812        8780      10000          8775
     0.90          8239       8297        8214      10000          8186
     1.00          7558       7699        7562      10000          7462
     1.10          6780       7044        6792      10000          6618
     1.20          5859       6304        5955      10000          5656
     1.30          4816       5441        5010      10000          4616
     1.40          3822       4681        4176      10000          3612
     1.50          2848       3851        3286      10000          2643
     1.60          2047       3092        2512      10000          1856
     1.70          1380       2437        1831      10000          1224
     1.80           920       1858        1333      10000           795
     1.90           592       1363         892      10000           518
     2.00           326        916         578      10000           278
     2.10           194        596         343      10000           154
     2.20           127        363         194      10000           103
     2.30            59        208         101       9986            45
     2.40            33        128          54       9930            25
     2.50            13         66          21       9814             9
     2.60             7         21           9       9433             5
     2.70             2          7           2       8706             1
     2.80             3          5           3       7563             3
     2.90             0          0           0       5989             0
     3.00             1          1           0       4318             0
     3.10             0          0           0       2784             0
     3.20             0          0           0       1576             0

In [21]:
df.to_csv("tmp.csv")